version: 2
defaults: &defaults
  working_directory: ~/project
  docker:
  - image: quay.io/wework/wem2k-server:master
    auth:
      username: $DOCKER_USER
      password: $DOCKER_PASSWD

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: wem2k-npm-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: wem2k-npm-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run linter
          command: npm run lint-ci
      - store_artifacts:
          path: reports
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: wem2k-npm-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: wem2k-npm-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
          environment: 
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports

  push:
    docker:
      - image: circleci/buildpack-deps
    environment:
      - DOCKER_REPOSITORY: 'quay.io/wework/wem2k-server'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker push
          command: |
            .circleci/docker_push

workflows:
  version: 2
  wem2k_workflow:
    jobs:
      - lint:
          context: org-global
      - test:
          context: org-global
      - push:
          context: org-global
          requires:
            - lint
            - test
          filters:
            branches:
              only: master

notify:
  webhooks:
  # Post the build result to starcatcher for ETL.
  - url: https://starcatcher-staging.herokuapp.com/webhooks/circleci_build
